# print('hello world!')
# print('好好学习')
# a = input('你的年龄：')
# print(a)
# print(555)
# print(3.55)
# print(False)
# print(())
# print([])
# print({})
# print('我想你了',23,3.58,False)
# print('你是我情深似海'+'的yilai')
# print('学习'*10)
# print(((5+15)*3-50)/5)
# print(3<8)
# name = '张三'
# print(name)
# a = input('请输入:')
# print('您今年多大了:',a)
# a = input('请输入：')
# b = input('请输入：')
# print(a+b)
# print(type('很好的'))
# print(type(23))
# print(type(5.5))
# print(type(False))
# print(type(()))
# print(type([]))
# print(type({}))
# a = '2.333'
# print(type(a))
# print(len(a))

# print(type(str(False)))
a = input('请输入：')
b = input('请输入：')
print('两端字符串的长度是：',len(a)+len(b))